"""empty message

Revision ID: 35178be29755
Revises: 
Create Date: 2022-11-06 11:07:36.816090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35178be29755'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('typeDocument', sa.String(length=50), nullable=True),
    sa.Column('numDocument', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('lastaName', sa.String(length=200), nullable=True),
    sa.Column('hobbie', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
