"""empty message

Revision ID: 7d5f5bc18638
Revises: 35178be29755
Create Date: 2022-11-06 22:16:42.614855

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7d5f5bc18638'
down_revision = '35178be29755'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('lastName', sa.String(length=200), nullable=True))
    op.drop_column('user', 'lastaName')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('lastaName', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('user', 'lastName')
    # ### end Alembic commands ###
